version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./clip_embedder/faiss_indexes:/app/clip_embedder/faiss_indexes
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    command: streamlit run streamlit_app.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend

  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    ports:
      - "18152:5432"
    environment:
      POSTGRES_DB: clipdb  # creates clipdb automatically
      POSTGRES_USER: clipuser
      POSTGRES_PASSWORD: clippass
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgvector_data:
