name: image_search
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - faiss-gpu
  - pandas
  - opencv
  - streamlit
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pytorch=2.6.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # CUDA 11.8 환경에 맞춤