name: image_search
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - faiss-gpu
  - pandas
  - opencv
  - streamlit
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
